version: '2'

services:
  producer:
    image: shipperizer/silver-giggle:dev
    command: make producer
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_RDB_HOST=0.0.0.0
      - CELERY_NAME=producer
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  beat:
    image: shipperizer/silver-giggle:dev
    command: make beat
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_NAME=beat
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  service-a:
    image: shipperizer/silver-giggle:dev
    command: make consumer
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_NAME=service-a
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  service-b:
    image: shipperizer/silver-giggle:dev
    command: make consumer
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_NAME=service-b
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  service-c:
    image: shipperizer/silver-giggle:dev
    command: make consumer
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_NAME=service-c
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  service-d:
    image: shipperizer/silver-giggle:dev
    command: make consumer
    build:
      dockerfile: config/Dockerfile
      context: .
    environment:
      - BROKER_CNX_STRING=amqp://rabbit:rabbit@rabbitmq:5672//
      - CELERY_NAME=service-d
    depends_on:
      - rabbitmq
    volumes:
      - ./:/var/app
      - /var/app/.git

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 15672
